title: Youngmin Kim
logo: /assets/img/my_photo.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
url: https://winston1214.github.io
